### ISSUE TITLE
Apache server is not starting

### ISSUE THREAD

**Issue by cemartins70** [OCSInventory-NG/OCSInventory-Server#441] opened 2023-10-05 13:08 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :
Linxu Debian 12

### Server informations
Perl version :
V5 Version 36
Mysql / Mariadb / Percona version :  
MariaDB Version 10.11.3

### OCS Inventory informations
Ocs server version : Versio 2.12.0

### Problem's description
In the migration process from Debian 11 to Debian 12 the apache server is not restarting.

Error:
out 04 20:40:25 OCSInventory apachectl[2559]: [Wed Oct 04 20:40:25.021011 2023] [perl:error] [pid 2559] Can't locate Apache/Ocsinventory/Plugins.pm in @INC (you may need to install the Apache::Ocsinventory::Plugins module) (@INC contain>
out 04 20:40:25 OCSInventory apachectl[2559]: [Wed Oct 04 20:40:25.021673 2023] [perl:error] [pid 2559] Can't load Perl module Apache::Ocsinventory::Plugins for server (null):0, exiting...

**Comment by miky2k** [comment] 2023-11-23 13:35
Same here Ubuntu 18.04  ubuntu 20.04

[Thu Nov 23 14:26:57.714319 2023] [perl:error] [pid 77456] Can't locate Apache/Ocsinventory/Plugins/Apache.pm in @INC (you may need to install the Apache::Ocsinventory::Plugins::Apache module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /etc/apache2) at (eval 16) line 1.\n
[Thu Nov 23 14:26:57.714424 2023] [perl:error] [pid 77456] Can't load Perl module Apache::Ocsinventory::Plugins::Apache for server Linux02.caim.local:0, exiting...

**Comment by Lea9250** [comment] 2023-12-05 13:53
Hi @cemartins70,

Are the server files present in any of the paths in your @INC ?

Regards,
Léa

**Comment by Lea9250** [comment] 2024-05-15 12:43
Hi @cemartins70 

I'm closing this since there was no answer but feel free to reopen if the issue is still relevant.

Regards,
Léa

**Closed by Lea9250** 2024-05-15 12:43 UTC
