### ISSUE TITLE
DBD::mysql::db do failed: Duplicate entry '1211271' for key 'PRIMARY' at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update/AccountInfos.pm line 66

### ISSUE THREAD

**Issue by ChrisWelcome** [OCSInventory-NG/OCSInventory-Server#136] opened 2018-09-20 07:44 UTC
### OCS Inventory informations
Ocs server version :  2.5

### Problem's description

DBD::mysql::db do failed: Duplicate entry '1211271' for key 'PRIMARY' at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update/AccountInfos.pm line 66

it looks like, the system attempt to insert accountinfo at every time, also when the system still exist.
in the code, i found no check, if the entry is allready existing.

best regards

Chris

**Comment by cargemail** [comment] 2019-08-13 21:46
Run this commad on your mysql server:
ALTER TABLE softwares MODIFY ID bigint;
ALTER TABLE softwares MODIFY ID bigint(20) AUTO_INCREMENT;
ALTER TABLE networks ADD MTU varchar(255) NULL AFTER speed;

**Comment by ChrisWelcome** [comment] 2019-08-14 09:04
At the moment we have on the Software table:
  `ID` bigint(11) NOT NULL AUTO_INCREMENT,

At network table we have allready, the mtu column:
  `MTU` varchar(255) DEFAULT NULL,

You are sure, that we have to update the ID Column to bigint(20). 
For me the error message and the code in the accountinfos.pm only for "inserting accountinfo id".

best regards

Chris

**Comment by cargemail** [comment] 2019-08-14 13:17
I work in a medium-sized company, there are 3,500 Windows desktops. Then, the software table grows very fast, this caused us to have an error: out of value for the column ... After we modified the database schema, those errors were corrected.

**Comment by gillesdubois** [comment] 2020-09-03 14:13
Hi,

It seem that the problem is now solved thus i'm closing the issue.

Regards,
Gilles.

**Closed by gillesdubois** 2020-09-03 14:13 UTC
