### ISSUE TITLE
LDAPS error

### ISSUE THREAD

**Issue by BadouDream** [OCSInventory-NG/OCSInventory-Server#442] opened 2023-10-05 18:05 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Rocky 9.2

### Server informations
Perl version : 5.32.1
Mysql / Mariadb / Percona version :  Mariadb 10.5.16

### OCS Inventory informations
Ocs server version : 2.12.1

### Problem's description
LDAP connection (not anonymous) work. But when I change protocol ldap by ldaps and port 389 to 636, I have a blank page when I validate my login.
In log/php-fpm/www-error.log, I have this error : 
[05-Oct-2023 19:26:48 Europe/Paris] PHP Fatal error:  Uncaught TypeError: ldap_search(): Argument #1 ($ldap) must be of type LDAP|array, bool given in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php:83
Stack trace:
#0 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(83): ldap_search()
#1 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(66): search_on_loginnt()
#2 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php(45): verif_pw_ldap()
#3 /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/auth.php(100): require_once('...')
#4 /usr/share/ocsinventory-reports/ocsreports/require/header.php(321): require_once('...')
#5 /usr/share/ocsinventory-reports/ocsreports/index.php(44): require('...')
#6 {main}
  thrown in /usr/share/ocsinventory-reports/ocsreports/backend/AUTH/methode/ldap.php on line 83

ldap.conf is not located at /etc/ldap/ldap.conf but in /etc/openldap/ldap.conf. I have all prerequis. 

I have GLPI on this same server and it's work perfect in LDAPS with SSO.
Can you help me ? 

Thanks

**Comment by Lea9250** [comment] 2023-12-11 15:40
Hi @BadouDream, 

Would you be able to try and edit your var.php file, setting AUTH_LDAP_SKIP_CERT to true ? It will skip the certificate verification and allow you to test ldap auth again, see if the issue might be coming from the certificate.

Regards, 
Léa

**Comment by Lea9250** [comment] 2024-05-15 12:44
Hi @BadouDream 

I'm closing this since there was no answer but feel free to reopen if the issue is still relevant.

Regards,
Léa

**Closed by Lea9250** 2024-05-15 12:44 UTC
