### ISSUE TITLE
HTTP Stats Code #400. Agent will not communicate with server. 

### ISSUE THREAD

**Issue by keeper05** [OCSInventory-NG/OCSInventory-Server#440] opened 2023-10-02 20:34 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :
RHEL 8 
### Server informations
Perl version : v5.26.3
Mysql / Mariadb / Percona version :  Ver 15.1 Distrib 10.3.35-MariaDB

### OCS Inventory informations
Ocs server version : 2.12 installed via RPM

### Problem's description
I am unable to get the Windows Agent (20.10.1.0) to connect to the server. I receive a HTTP 400 error. Below is the relevant part of the agent log and ini.

COM SERVER => Sending fileGet request to URL <http://server_IP_Address/ocsinventory/deploy/label>

COM SERVER => fileGet response received <HTTP Status Code #400>

COM SERVER => Cleaning cURL library

AGENT => Failed to retrieve Label <HTTP Status Code #400>

AGENT => Sending Prolog

DID_CHECK => Read DeviceID <client_machine-2023-09-22-16-31-23> and MACs <xx:xx:xx:xx:xx:xx> in file <ocsinventory.dat>

COM SERVER => Initializing cURL library for sendRequest

COM SERVER => Using cURL without server authentication

COM SERVER => Disabling cURL proxy support

COM SERVER => Disabling cURL SSL server validation support

COM SERVER => Sending HTTP Post request to URL <http://server_IP_Address/ocsinventory>

COM SERVER => HTTP Post response received <HTTP Status Code #400>

COM SERVER => Cleaning cURL library

**_Most issues with HTTP Status Code #400 are due to the Agent version being higher than the server version. This is not the case here.
Agent ini file looks like this:_**

[OCS Inventory Agent]

ComProvider=ComHTTP.dll

Debug=1

Local=

NoSoftware=0

HKCU=0

NoTAG=0

IpDisc=

WMI_FLAG_MODE=COMPLETE

DEFAULT_USER_DOMAIN=

[HTTP]

Server=http://server_IP_Address/ocsinventory

SSL=0

CaBundle=cacert.pem

AuthRequired=0

User=

Pwd=

ProxyType=0

Proxy=

ProxyPort=0

ProxyAuthRequired=0

ProxyUser=

ProxyPwd=

[OCS Inventory Service]

TTO_WAIT=1020

INVENTORY_ON_STARTUP=0

**Comment by Lea9250** [comment] 2023-10-05 08:59
Hi @keeper05 ,

Do you have any logs referring to this on the server ? You'll want to look at the apache error log and the activity log populated by OCS (/var/log/ocsinventory-server/activity.log). If not already done, you'll need to enable LOGLEVEL under Configuration > Server from the GUI. 
For debugging purposes you can also set the OCS_OPT_DBI_PRINT_ERROR to 1 in /etc/apache2/conf-enabled/z-ocsinventory-server.conf, restart the apache service and then trigger an inventory of your computer before checking the logs.

Let me know how this goes.

Léa

**Comment by Lea9250** [comment] 2023-10-30 16:04
Hi @keeper05,

Any update on this matter ?

Regards, 
Léa

**Comment by keeper05** [comment] 2023-11-15 20:59
Yes Lea. I was unable to get it working via http. I ended up having to go
to the SSL route due to this issue. As I had stated in the issue, the
symptoms are indicative of using a new agent than the server version.

**Comment by Lea9250** [comment] 2023-12-05 13:32
Hi @keeper05, 

I'll close this since the issue is no longer reproducible but feel free to reopen if you end up with the same problem at some point. 
As a side note, the fact that you were able to send inventory through https makes me think of an apache configuration issue, but that would depend on whether or not you had modified the "default" ocs configuration files and how.
For agent vs server version conflicts though, the activity.log of the server (see previous message for enabling) usually gives a warning if there is any. 

Best regards, 
Léa

**Closed by Lea9250** 2023-12-05 13:32 UTC

**Comment by keeper05** [comment] 2023-12-05 13:57
I had no issues accessing the dashboard via http. The agents just wouldn’t connect via http. On Dec 5, 2023, at 08:32, Lea9250 ***@***.***> wrote:﻿
Hi @keeper05,
I'll close this since the issue is no longer reproducible but feel free to reopen if you end up with the same problem at some point.
As a side note, the fact that you were able to send inventory through https makes me think of an apache configuration issue, but that would depend on whether or not you had modified the "default" ocs configuration files and how.
For agent vs server version conflicts though, the activity.log of the server (see previous message for enabling) usually gives a warning if there is any.
Best regards,
Léa
