### ISSUE TITLE
new network interface is not inventoried

### ISSUE THREAD

**Issue by thfiliol1** [OCSInventory-NG/OCSInventory-Server#336] opened 2021-06-23 07:51 UTC
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : CentOS 7

### Server informations
Perl version : 5.16.3
Mysql / Mariadb / Percona version :  MariaDB Server version 10.5.6
PHP: 7.3.11

### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
2 network cards are added on a PC.
One of the cards has been added in few days later after the first inventory. But this new card is never inventoried... To force that I have to delete the machine on the OCS Server and when the machine appears there are 2 cards.
I think there is a problem to update network interface when machine exists 
![screen_info](https://user-images.githubusercontent.com/15216061/123057715-65579e80-d408-11eb-9c47-246ef8e8d0b6.jpg)
![screen_info_ocs](https://user-images.githubusercontent.com/15216061/123057742-6b4d7f80-d408-11eb-8eaf-4aad96196b71.jpg)

**Comment by thfiliol1** [comment] 2021-06-23 07:56
And I have an other problem, when the second network interface have no default gateway the agent copy the gateway of the first network interface. Moreover on the second network interface the ip address of network is not correct...

**Comment by charleneauger** [comment] 2023-03-27 13:54
Hi @thfiliol1 ,

Many fixes/improvements have been made since version 2.8.
Can you tell me if the problem is still present with the latest Agent/Server versions ?

Best regards,
Charlene

**Comment by charleneauger** [comment] 2023-05-22 12:18
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene

**Closed by charleneauger** 2023-05-22 12:18 UTC
