### ISSUE TITLE
No hash password

### ISSUE THREAD

**Issue by larieu** [OCSInventory-NG/OCSInventory-Server#31] opened 2016-11-28 19:00 UTC
creating a user or alter a old one will prompt this errors in error_log ( apache ) 

> [Mon Nov 28 19:19:05 2016] [error] [client 192.168.254.235] PHP Warning:  constant(): Couldn't find constant  in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 115, referer: http://ocs.mydomain.com/ocsreports/index.php?function=admin_user_details&user_id=ion.ionescu
> [Mon Nov 28 19:19:05 2016] [error] [client 192.168.254.235] PHP Warning:  password_hash(): Unknown password hashing algorithm: 0 in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 115, referer: http://ocs.mydomain.com/ocsreports/index.php?function=admin_user_details&user_id=ion.ionescu

(domain and user altered) 

and the user cannot login any more

server
linux CentOS 6 - last update
uname -a
ocs.mydomain.com 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

httpd -v
Server version: Apache/2.2.15 (Unix)
Server built:   Nov 18 2016 23:48:5

php -v
PHP 5.6.28 (cli) (built: Nov 10 2016 21:09:50) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by gillesdubois** [comment] 2016-11-28 19:09
Hi, 

Which ocs version are you using ?

Regards,
Gilles Dubois.

**Comment by larieu** [comment] 2016-11-28 20:35
2.3


Operating system

    OS Name :      Linux x86_64
    Version :        2.6.32-642.11.1.el6.x86_64
    RAM installed :      3832 Mo
    Free RAM :
    CPU :           Common KVM processor
    Distribution :      CentOS release 6.8 (Final)

Software

    PHP Version :     5.6.28 (apache2handler)
    Web Server :     Apache/2.2.15 (CentOS)
    Database Server :     Source distribution version 5.1.73
    Version OCSReports:      2.3

**Comment by larieu** [comment] 2016-11-28 21:08
if I push a "known" hash in sql the user will work OK
but any attempt to change from web gui will push a "empty" hash in passwd field and the user is no long accepted to login

**Comment by gillesdubois** [comment] 2016-11-29 08:11
Hi,

Can you post me your apache2 error_log ?

PS : Using the trunk version is not recommanded if you are in an production environement you should use stable releases only.

**Comment by larieu** [comment] 2016-11-29 09:27
To take the latest update 

I've done like that

enter 
http://www.ocsinventory-ng.org/en/
on the Download > GITHUB
points me to 
https://github.com/OCSInventory-NG
found the server for linux
https://github.com/OCSInventory-NG/OCSInventory-Server
clone with git clone on my server
get inside that folder
copied inside with git also the ocsreports
git clone https://github.com/OCSInventory-NG/OCSInventory-ocsreports.git ocsreports
install with provided script 
found that even no error occurred during the update - the interface not shown
after a bit of debugging I found that the interface used php code for 5.4x 
I just update the 5.3.3. (default on my distribution ) with 5.6.28 
everything seems to be ok in the first moment

for the logs - How I can push them in a "safe" place?

**Comment by gillesdubois** [comment] 2016-11-29 14:44
Could you try re-build your ocs using the last trunk sources ?
Some fixes has been made in the user creation form.

I don't need any additional log.
I will investigate the issue soon.

Regards,
Gilles Dubois

**Comment by larieu** [comment] 2016-11-29 20:33
Can you be a bit more specific. I'm not a developer 
I am skilled enough to do lots of damage but I am not able to follow that comment
if you write down some steps I can try

**Comment by gillesdubois** [comment] 2016-11-30 09:18
Hi, 

Sorry my comment wasn't rly clear.
Just repeat the steps above to recreate an update to date ocsinventory installation : 

- Git clone ocsinventory-server
- Git clone ocsinventory-reports in the ocsinventory-server folder as ocsreports 
- Install / Update ocsinventory
- Try your user problems again.

Thanks you for contributing ocsinventory project.

Regards,
Gilles Dubois.

**Comment by larieu** [comment] 2016-11-30 10:41
Ok - done it , 
result : "the same"


> [Wed Nov 30 12:22:50 2016] [error] [client 192.168.254.235] PHP Warning:  constant(): Couldn't find constant  in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 139, referer: http://ocs.mydomain.com/ocsreports/index.php?function=admin_add_user
> [Wed Nov 30 12:22:50 2016] [error] [client 192.168.254.235] PHP Warning:  password_hash(): Unknown password hashing algorithm: 0 in /usr/share/ocsinventory-reports/ocsreports/require/function_users.php on line 139, referer: http://ocs.mydomain.com/ocsreports/index.php?function=admin_add_user
> 

steps

01. create a new folder for install/backup
mkdir -p ~/ocsYYYYMMDD/bkp
02. enter new folder
cd ~/ocsYYYYMMDD/bkp
03. backup php.ini, z-...conf, ocs...conf , stop ocs , bakup database
cp /etc/php.ini ./
mv /etc/httpd/conf.d/ocsinventory-reports.conf ./
mv /etc/httpd/conf.d/z-ocsinventory-server.conf ./
/etc/init.d/httpd restart
mysqldump -u root -p ocsweb > ocsweb.sql
04. enter the root folder and bring git data
cd ~/ocsYYYMMDD
git clone https://github.com/OCSInventory-NG/OCSInventory-Server
cd OCSInventory-Server/
git clone https://github.com/OCSInventory-NG/OCSInventory-ocsreports.git ocsreports
cd ..
05. run the install
./setup.sh
06. modify the z-ocs...conf with my credentials /database name .... 
vi (nano,mcedit,vim...) /etc/httpd/conf.d/z-ocsinventory-server.conf
07. restart apache
/etc/init.d/httpd restart
08. point browser to ocsreports, insert credentials > OK
09. move install.php
mv /usr/share/ocsinventory-reports/ocsreports/install.php /usr/share/ocsinventory-reports/ocsreports/whatewerUwant.php_bak
10. start a tail  for error_log
tail -f /var/log/httpd/error.log
11. go to user management - create new user teste.test

error in error.log ( at the beginning of post ) 

in sql 
select * from operators;
 | teste.test        | Test      | DeTest   |                                                              |      NULL |                               | admin         |                                |            |                0 |


should I try to go to php 7?

**Comment by larieu** [comment] 2016-11-30 10:53
New info 
I have for example an not_used.user
which I know he pass known_pass
in sql looks like this

`| not-used.user | Not-Used | User | 0123456789abcdefghijklmnopqrstuvx | NULL | | admin | | | 0 |`

after first login of the user 

it is transformed into something like this

`| not-used.user | Not-Used | User | 2y$10$0123456789abcdefghijklmnopqrstuvxyzABCDEFGHIJKMNOPQRSTU | NULL | | admin | | | 1 |`

that means  transformation form old type to new one works 
only creating in the first stage won't 

could it be a quick fix to generate "old_type" at the user creation/ reset pass process?

**Comment by gillesdubois** [comment] 2016-11-30 13:11
Hi,

php5 and php7 are supported you can stick with your actual php version.
Before you upgraded to 2.3 which ocs version were you running ?

I will try to create an environement as close as yours to reproduce the bug.

Regards,
Gilles Dubois.

**Comment by larieu** [comment] 2016-11-30 20:06
From  what I remember 2.1.1. ( let's say 95% sure ) installed on CentOS 6.4 ( that was the "last" on the time I installed it ) 
I plan to install a 2.1.2.  on other VM and change name to point on the other one 
this will port all active computers on the new server
when this became "free" I can arrange access to it 
this will give you "first hand" to debug

**Comment by gillesdubois** [comment] 2016-12-06 08:26
Hi,

I checked your issue recently, i can't reproduce the problems but this come from your sessions variables ...
Could you edit one of your file and try again plz ?

You have to edit function_users.php ( in require folder ) on line 115.

Replace : 
`$arg_update[] = password_hash($password, constant($_SESSION['OCS']['PASSWORD_ENCRYPTION']));`

By :
`$arg_update[] = password_hash($password, 1);`

**Comment by larieu** [comment] 2016-12-07 02:49
doing this, both user change and new user creation works
no error occur in httpd/error_log and in mysql the pass field is not empty and user can login 
this seems to "fix" the issue 
most probably is related to the PHP forded update 
it remain the other 3 problems (2 of them already in separate threads) 
1 - the fact that I am not able to mass deploy a package (#32)
2 - the fact the network information is not shown in the appropriate place (#33)
3 - the fact a new computer with proper installed client does not register (error 550 ) 
- changing an old one works 
- having a 2.1.2 version replacing the 2.3 version that computer register no issue ( 2 separate VM ) 
do you think is worth to try on a new CentOS7 to try the 2.3 version?

**Comment by gillesdubois** [comment] 2016-12-07 08:27
Hi,

Thanks for your report.

1 - The 2.3 version is not a finished one so you might experience some bugs depending on when you created your ocsinventory install.
Deployments package are not in the configuration menu of a computer anymore but in the deployment menu.

2 - The web interface is just displaying information retrivied with the agent, maybe your agent doesn't retrieve any network data at all ?
![networks](https://cloud.githubusercontent.com/assets/9396603/20960064/ce9617a8-bc5e-11e6-908b-f9941f43fc12.png)
As you can see in the screen above i got networks entries on my web console.

3 - Http status 550 is for "Permission Denied"
Maybe your web server is not well configured ?

At the moment i think you should wait a few days ( 2.3 is releasing as a RC soon ) and then upgrade from your clean 2.1.2 version to the 2.3RC.

Thanks for your contribution.

Regards,
Gilles Dubois.

**Comment by larieu** [comment] 2016-12-07 11:32
1. Mass deploy 
described here
https://github.com/OCSInventory-NG/OCSInventory-Server/issues/32

it works for **one** computer in the Deploy menu 
Doesn't work if I select 1 or several computers after I have filtered with the search tool , or from selection in the "all computer" menu 

it loops like in description
"for selection" > "no advacned..." > back again to "for selection" > "no advanced" >..... > 

2. Network
https://github.com/OCSInventory-NG/OCSInventory-Server/issues/33

in version 2.1.1. it is all OK - I can see network cipset, mac,.... 
after upgrade 
If i select in "all computers" the mac address column - I have the mac address well shown
but in the "hardware" side of the computer at the network is nothing (no data available ) 
as long in "all computer I can see the mac address - is odd to not have data available here

3. 
if I change name of one computer , or if I change the NIC ( I put an add on card ) , or I put a videocard and I use  it instead of the onboard card  - I can see the changes ( the mac only in the mac column of the "all computer" form ) but a new computer is not able to register 
- ONLY NEW ONES are with problem

**Comment by gillesdubois** [comment] 2016-12-28 13:42
Hi,

This issue has been resolved. 
I will start investigate your others issue from now. ( #32 #33 )

The 2.3 RC is now out you should try to upgrade from your clean 2.1.2 to the 2.3RC somes fix has been done on network / deploy actions.

Regards,
Gilles Dubois

**Closed by gillesdubois** 2016-12-28 13:42 UTC
Labels: question
