### ISSUE TITLE
[FEATURE] Add CVE data in the json of computer rest api

### ISSUE THREAD

**Issue by dust63** [OCSInventory-NG/OCSInventory-Server#249] opened 2020-08-31 09:26 UTC
Like softwares or plugin data, can you add CVE data on computer route rest api. http://myocsserver/ocsapi/v1/computer/{ID}

**Comment by charleneauger** [comment] 2020-12-11 09:41
Hi @dust63 

I close this issue because it's a duplicate of your other issue #247 

Regards,
Charlene

**Closed by charleneauger** 2020-12-11 09:41 UTC
